name: yolo
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - alabaster=0.7.12
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - astroid=2.5
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.25
  - cachetools=4.2.1
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - coverage=5.5
  - cryptography=3.4.6
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cycler=0.10.0
  - cython=0.29.22
  - decorator=4.4.2
  - defusedxml=0.7.1
  - dlib=19.21.1
  - docutils=0.16
  - entrypoints=0.3
  - freetype=2.10.4
  - gast=0.2.2
  - google-auth=1.27.1
  - google-auth-oauthlib=0.4.3
  - google-pasta=0.2.0
  - graphviz=2.38
  - grpcio=1.36.1
  - h5py=2.8.0
  - hdf5=1.8.20
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - isort=5.8.0
  - jedi=0.17.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - keyring=22.3.0
  - kiwisolver=1.3.1
  - lazy-object-proxy=1.6.0
  - libopencv=3.4.2
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libuv=1.40.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - multidict=5.1.0
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.5.1
  - notebook=6.2.0
  - numpy=1.19.2
  - numpy-base=1.19.2
  - numpydoc=1.1.0
  - oauthlib=3.1.0
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1k
  - opt_einsum=3.1.0
  - packaging=20.9
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.1
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=21.0.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - protobuf=3.14.0
  - psutil=5.8.0
  - py-opencv=3.4.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pyflakes=2.3.0
  - pygments=2.8.1
  - pyjwt=1.7.1
  - pylint=2.7.2
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2021.1
  - pywin32=227
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.7
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtawesome=1.0.2
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rope=0.18.0
  - rsa=4.7.2
  - scikit-learn=0.24.1
  - scipy=1.6.1
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - snowballstemmer=2.1.0
  - sphinx=3.5.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=3.3.6
  - spyder-kernels=0.5.2
  - sqlite=3.35.0
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=1.15.0
  - tensorflow-base=1.15.0
  - tensorflow-estimator=1.15.1
  - tensorflow-gpu=1.15.0
  - termcolor=1.1.0
  - terminado=0.9.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - typed-ast=1.4.2
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.12.1
  - xz=5.2.5
  - yarl=1.6.3
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - cmake==3.18.4.post1
    - fire==0.4.0
    - imageprep==0.3
    - keras2onnx==1.7.0
    - llvmlite==0.36.0
    - numba==0.53.1
    - onnx==1.9.0
    - onnxconverter-common==1.8.1
    - onnxruntime==1.7.0
    - pandas==1.2.3
    - panns==0.2.0
    - pydot==1.4.2
    - pydotplus==2.0.2
    - pynndescent==0.5.2
    - python-graphviz==0.16
